-- Run this query in the Supabase Dashboard > SQL Editor
-- This changes the 'score' column type in 'mock_history' from integer to double precision
-- to support decimal scores (e.g. 14.25) which are generated by medicine exam scoring rules (-0.25 for wrong answers).

ALTER TABLE public.mock_history 
ALTER COLUMN score TYPE double precision;
