-- SQL Patch: Create Error Logs Table for Monitoring
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.error_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE SET NULL,
  error_message text,
  error_stack text,
  component_stack text,
  url text,
  user_agent text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security
ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Anyone can insert error logs" ON public.error_logs;
DROP POLICY IF EXISTS "Admins can view error logs" ON public.error_logs;

-- Allow INSERT policy for anyone (authenticated or anonymous) to make sure no errors are missed
CREATE POLICY "Anyone can insert error logs" ON public.error_logs
  FOR INSERT WITH CHECK (true);

-- Allow SELECT/DELETE policy for admins only
CREATE POLICY "Admins can view error logs" ON public.error_logs
  FOR SELECT USING (public.is_admin());

CREATE POLICY "Admins can manage error logs" ON public.error_logs
  FOR ALL USING (public.is_admin());

-- Index for quick lookups and sorting
CREATE INDEX IF NOT EXISTS idx_error_logs_created_at ON public.error_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_error_logs_user_id ON public.error_logs(user_id);
