-- SQL Schema for L'Conq Supabase Migration
-- Copy and run this script in your Supabase SQL Editor (Dashboard > SQL Editor > New query)

-- 1. Profiles Table (linked to auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  name text,
  email text,
  role text default 'student',
  tier text default 'freemium',
  xp integer default 0,
  streak integer default 0,
  rank integer,
  total_students integer default 1200,
  joined timestamp with time zone default timezone('utc'::text, now()),
  subscription jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Helper function to check if a user is an admin
-- Defined as SECURITY DEFINER to bypass RLS policies when querying the profiles table
create or replace function public.is_admin()
returns boolean
security definer set search_path = public
language plpgsql as $$
begin
  return exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.role = 'admin'
  );
end;
$$;

-- Policies for Profiles
create policy "Users can view their own profile." on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile." on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Admins can do everything on profiles." on public.profiles
  for all using (public.is_admin());

-- Function and trigger to automatically create a profile when a user signs up
create or replace function public.handle_new_user()
returns trigger
security definer set search_path = public
language plpgsql as $$
begin
  insert into public.profiles (id, name, email, role, tier, xp, streak, total_students, joined)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', 'Élève'),
    new.email,
    'student',
    'freemium',
    0,
    0,
    1200,
    now()
  );
  return new;
end;
$$;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Config Table (for schools config, plans config, etc.)
create table if not exists public.config (
  key text primary key,
  value jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.config enable row level security;

create policy "Anyone can read configs." on public.config
  for select using (true);

create policy "Admins can write configs." on public.config
  for all using (public.is_admin());

-- 3. Exams Table
create table if not exists public.exams (
  id text primary key,
  name text not null,
  school text,
  year text,
  tier text,
  questions jsonb, -- array of questions
  pdf_url text,
  is_active boolean default true,
  is_archived boolean default false,
  date_added timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.exams enable row level security;

create policy "Anyone can view active and non-archived exams." on public.exams
  for select using (true);

create policy "Admins can manage exams." on public.exams
  for all using (public.is_admin());

-- 4. Activation Codes Table
create table if not exists public.activation_codes (
  code text primary key,
  plan_id text,
  is_used boolean default false,
  used_by text,
  used_at timestamp with time zone,
  batch_name text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.activation_codes enable row level security;

create policy "Authenticated users can select activation codes." on public.activation_codes
  for select using (auth.role() = 'authenticated');

create policy "Authenticated users can update activation codes." on public.activation_codes
  for update using (auth.role() = 'authenticated');

create policy "Admins can manage activation codes." on public.activation_codes
  for all using (public.is_admin());

-- 5. Progress Table (SRS/FSRS cards)
create table if not exists public.progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  question_id text not null,
  difficulty double precision,
  stability double precision,
  repetitions integer,
  ease_factor double precision,
  last_review_date timestamp with time zone,
  next_review_date timestamp with time zone,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, question_id)
);

alter table public.progress enable row level security;

create policy "Users can manage their own progress." on public.progress
  for all using (auth.uid() = user_id);

-- 6. Mock History Table
create table if not exists public.mock_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  exam_id text not null,
  exam_name text,
  school text,
  score integer,
  max_score integer,
  pct double precision,
  correct_count integer,
  wrong_count integer,
  empty_count integer,
  mode text,
  date timestamp with time zone default timezone('utc'::text, now())
);

alter table public.mock_history enable row level security;

create policy "Users can manage their own mock history." on public.mock_history
  for all using (auth.uid() = user_id);

-- 7. Activity Table
create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  date date not null default current_date,
  count integer default 1,
  unique(user_id, date)
);

alter table public.activity enable row level security;

create policy "Users can manage their own activity." on public.activity
  for all using (auth.uid() = user_id);

-- 8. Profile Update Protection Trigger
-- Prevents non-admin users from changing their own role or tier
create or replace function public.check_profile_update()
returns trigger
security definer set search_path = public
language plpgsql as $$
begin
  if (old.role is distinct from new.role or old.tier is distinct from new.tier) then
    if not (exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )) then
      new.role := old.role;
      new.tier := old.tier;
    end if;
  end if;
  return new;
end;
$$;

create or replace trigger check_profile_update_trigger
  before update on public.profiles
  for each row execute procedure public.check_profile_update();
